### ISSUE TITLE
php-coveralls dev-master -> no matching package found

### ISSUE THREAD

**Issue by cameronsloan** [antaresproject/installation#7]
Having some trouble creating the project with composer:

This happened in both the automated install and the manual install.  With the manual install, this was the command that eventually lead to the error:
composer -vvv create-project antaresproject/project /var/www/html dev-master --keep-vcs

Tried with automatic install and manual install on fresh copy of Ubuntu 16.04.3 LTS (min install with SSH)
I am finding that other projects on github are failing with  package with  satooshi/php-coveralls  dev-master
(https://github.com/php-coveralls/php-coveralls/issues/252)

Resolving dependencies through SAT
Dependency resolution completed in 0.012 seconds
Reading /root/.cache/composer/repo/https---packagist.org/provider-satooshi$php-coveralls.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-satooshi$php-coveralls.json from cache
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - antaresproject/core 0.9.2.x-dev requires satooshi/php-coveralls dev-master -> no matching package found.
    - antaresproject/core 0.9.2.x-dev requires satooshi/php-coveralls dev-master -> no matching package found.
    - Installation request for antaresproject/core 0.9.2.x-dev -> satisfiable by antaresproject/core[0.9.2.x-dev].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by mountstone** [comment]
@cameronsloan 

Thank you for your message. :beer:

We have updated a `composer.json` file, which uses valid `php-coveralls/php-coveralls` repo from now, instead of `satooshi/php-coveralls`.

We have also updated `.env.example` file to use valid `COMPOSER_HOME` env variable, which has  thrown following error:

"Composer error: "The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly"

and occurs with new version of composer package.

Missing "languages" alias has been fixed also.

Please try to launch app installation once again.
